#
# organization wide configuration for release-drafter
#

name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION

categories:

  - title: ':boom: Breaking changes'
    when:
      label: 'breaking changes'

  - title: ':fire: New features'
    when:
      label: 'enhancement'

  - title: ':exclamation: Deprecated features'
    when:
      label: 'deprecation'

  - title: ':lady_beetle: Bug Fixes'
    when:
      label: 'bug'

  - title: ':hammer: Maintenance'
    when:
      labels:
        - 'code quality'
        - 'documentation'

  - title: ':toolbox: Dependency updates'
    collapse-after: 0
    exclusive: true
    when:
      label: 'dependencies'

  - type: 'pre-exclude'
    when:
      label: 'invalid'

change-template: '- $TITLE ([#$NUMBER]($URL)) @$AUTHOR'

sort-direction: 'ascending'

exclude-contributors:
  - 'dependabot'
  - 'dependabot[bot]'
  - 'GitHub Action'

template: |
  # What's Changed

  $CHANGES

  # :heart: Thanks
  Many thanks for collaboration on this release for: $CONTRIBUTORS
