#
# organization wide configuration for release-drafter
#
categories:

  - title: ':fire: New features'
    labels:
      - 'enhancement'

  - title: ':boom: Breaking changes'
    labels:
      - 'breaking changes'

  - title: ':exclamation: Deprecated features'
    labels:
      - 'deprecation'

  - title: ':lady_beetle: Bug Fixes'
    labels:
      - 'bug'

  - title: ':hammer: Maintenance'
    labels:
      - 'code quality'
      - 'documentation'

  - title: ':toolbox: Dependency updates'
    labels:
      -  'dependencies'

change-template: '- $TITLE #$NUMBER'

sort-direction: 'ascending'

template: |
  # What's Changed

  $CHANGES

  # :heart: Thanks
  Many thanks for collaboration on this release for: $CONTRIBUTORS
