name: 'Setup'
description: 'Common Project properties'

outputs:
  branch:
    description: ''
    value: ${{ steps.setup.outputs.branch }}
  date-ym:
    description: ''
    value: ${{ steps.setup.outputs.date-ym }}
  sonar:
    description: ''
    value: '2de0e32b2b3108965f76a4713ba2028978c233ed'
  maven-matrix:
    description: ''
    value: ${{ steps.setup.outputs.maven-matrix }}
  maven-default:
    description: ''
    value: ${{ steps.setup.outputs.maven-default }}
  java-matrix:
    description: ''
    value: ${{ steps.setup.outputs.java-matrix }}
  java-default:
    description: ''
    value: ${{ steps.setup.outputs.java-default }}
  java-distribution-matrix:
    description: ''
    value: ${{ steps.setup.outputs.java-distribution-matrix }}
  java-distribution-default:
    description: ''
    value: ${{ steps.setup.outputs.java-distribution-default }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false

    - name: Read preoject environemnts
      shell: bash
      run: |
        if [ -f .github/build.env ]; then
          echo "Use project build.env"
          grep -e "^[A-Z_]\+=[0-9a-zA-Z\., \"\-]\+$" .github/build.env >> $GITHUB_ENV;
        fi

    - name: Set outputs
      shell: bash
      id: setup
      run: ${{ github.action_path }}/setup.sh
