name: 'Setup'
description: 'Common Project properties'

outputs:
  branch:
    description: ''
    value: ${{ steps.setup.outputs.branch }}
  tag:
    description: ''
    value: ${{ steps.setup.outputs.tag }}
  date-ym:
    description: ''
    value: ${{ steps.setup.outputs.date-ym }}
  sonar:
    description: ''
    value: ${{ steps.setup.outputs.sonar }}

runs:
  using: "composite"
  steps:
    - name: Set outputs
      shell: bash
      id: setup
      run: ${{ github.action_path }}/setup.sh
