name: Auto Approve

on:
  workflow_call:
    secrets:
      TECH_TOKEN:
        required: true


jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:

      - name: Dependabot metadata
        if: github.actor == 'dependabot[bot]'
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.3.0
        with:
          github-token: "${{ secrets.TECH_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        if: >
          github.actor == 'dependabot[bot]'
          && steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.TECH_TOKEN }}

      - name: Approve a PR
        if: >
          github.actor == 'dependabot[bot]'
          || github.actor == 'slawekjaranowski'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.TECH_TOKEN }}
