name: common-files-maven-sync

on:
  push:
    branches:
      - master
    paths:
      - 'common-files-maven/**'
      - '.github/workflows/common-files-maven-sync.yml'

jobs:

  sync:

    strategy:
      fail-fast: false
      matrix:
        repo:
          - s4u/jfatek
          - s4u/parent
          - s4u/pgp-keys-map
          - s4u/pgpverify-maven-plugin
          - s4u/sign-maven-plugin
          - s4u/sitemapxml-maven-plugin
          - s4u/slf4j-mock
          - s4u/testing

    runs-on: ubuntu-latest
    concurrency: repo-sync-${{ matrix.repo }}

    steps:
      - uses: actions/checkout@v5

      - uses: slawekjaranowski/github-action-file-sync@master
        with:
          GIT_EMAIL: 'github-actions@github.com'
          GIT_USERNAME: 'GitHub Action'
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPOSITORIES: ${{ matrix.repo }}
          FILES: common-files-maven/.
