name: Build

on:
  workflow_call:
    inputs:
      java-matrix:
        default: '["8", "11", "17", "21"]'
        required: false
        type: string

      java-default:
        default: '8'
        required: false
        type: string

      java-dist-matrix:
        default: '["zulu"]'
        required: false
        type: string

      java-dist-default:
        default: 'zulu'
        required: false
        type: string

      maven-matrix:
        default: '["3.9.11"]'
        required: false
        type: string

      maven-default:
        default: '3.9.11'
        required: false
        type: string

    secrets:
      SIGN_KEY:
        required: true

      SIGN_KEY_PASS:
        required: true

      MAVEN_GPG_KEY:
        required: true

      MAVEN_GPG_PASSPHRASE:
        required: true

      OSS_USER:
        required: true

      OSS_PASS:
        required: true

      TECH_TOKEN:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:

  setup:
    name: Setup
    runs-on: ubuntu-latest

    if: |
      startsWith(github.ref, 'refs/tags/')
      || !startsWith(github.event.head_commit.message , '[maven-release-plugin] prepare release')

    outputs:
      branch: ${{ steps.setup.outputs.branch }}
      tag: ${{ steps.setup.outputs.tag }}
      date-ym: ${{ steps.setup.outputs.date-ym }}
      sonar: ${{ steps.setup.outputs.sonar }}

    steps:
      - id: setup
        uses: s4u/.github/actions/setup@master

  verify:
    name: ${{ matrix.os.label }} jdk-${{ matrix.java }}-${{ matrix.java-dist }} mvn-${{ matrix.maven }}
    needs: setup

    runs-on: ${{ matrix.os.name }}
    continue-on-error: ${{ matrix.os.can-fail }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - name: ubuntu-latest
            label: Linux
            can-fail: false
          - name: windows-latest
            label: Windows
            can-fail: false
          - name: macOS-latest
            label: macOS
            can-fail: true
        java: ${{ fromJSON( inputs.java-matrix ) }}
        java-dist: ${{ fromJSON( inputs.java-dist-matrix ) }}
        maven: ${{ fromJSON( inputs.maven-matrix ) }}

    steps:
      - uses: s4u/setup-maven-action@v1.18.0
        with:
          checkout-fetch-depth: 0
          java-version: ${{ matrix.java }}
          java-distribution: ${{ matrix.java-dist }}
          maven-version: ${{ matrix.maven }}
          settings-sonatypeSnapshots: true
          settings-properties: |
            [
              {"sonar.login": "${{ needs.setup.outputs.sonar }}"},
              {"sonar.branch.name": "${{ needs.setup.outputs.branch }}"}
            ]
          cache-prefix: ${{ needs.setup.outputs.date-ym }}-
          cache-path-add: ~/.sonar/cache

      - name: sonar setup
        id: sonar
        run: echo "mvn-args=sonar:sonar -P coverage" >> $GITHUB_OUTPUT
        if: >
          matrix.os.name == 'ubuntu-latest'
          && matrix.java == '17'
          && matrix.java-dist == fromJSON( inputs.java-dist-matrix )[0]
          && matrix.maven == fromJSON( inputs.maven-matrix )[0]
          && github.repository_owner == 's4u'
          && startsWith( github.ref, 'refs/heads/')

      - run: mvn --errors --show-version verify ${{ steps.sonar.outputs.mvn-args }}
        env:
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

  site-test:
    name: Site - Test
    needs: setup

    runs-on: ubuntu-latest

    steps:
      - uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: ${{ inputs.java-default }}
          java-distribution: ${{ inputs.java-dist-default }}
          maven-version: ${{ inputs.maven-default }}
          settings-sonatypeSnapshots: true
          cache-prefix: ${{ needs.setup.outputs.date-ym }}-maven-site-

      - run: mvn --errors --show-version package site -Dmaven.test.skip=true
 
  deploy:
    name: Deploy
    concurrency: maven-deploy

    if: github.repository_owner == 's4u'

    needs: [ setup, verify, site-test ]

    runs-on: ubuntu-latest

    steps:
      - uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: ${{ inputs.java-default }}
          java-distribution: ${{ inputs.java-dist-default }}
          maven-version: ${{ inputs.maven-default }}
          settings-sonatypeSnapshots: true
          settings-servers: |
            [{
              "id": "sonatype-central-portal", 
              "username": "${env.OSS_USER}", 
              "password": "${env.OSS_PASS}",
              "configuration": {
                "njord.publisher": "sonatype-cp",
                "njord.releaseUrl": "njord:template:release-sca"
              }
            }]
          cache-prefix: ${{ needs.setup.outputs.date-ym }}-

      - run: mvn --errors --show-version deploy -Dnjord.enabled=true -Dmaven.test.skip=true
        env:
          OSS_USER: ${{ secrets.OSS_USER }}
          OSS_PASS: ${{ secrets.OSS_PASS }}
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

  site-deploy:
    name: Site - Deploy
    concurrency: site-deploy
    if: github.repository_owner == 's4u' && startsWith(github.ref, 'refs/tags/')

    needs: [ setup, deploy ]

    runs-on: ubuntu-latest

    steps:
      - uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: ${{ inputs.java-default }}
          java-distribution: ${{ inputs.java-dist-default }}
          maven-version: ${{ inputs.maven-default }}
          settings-sonatypeSnapshots: true
          settings-properties: |
            [
              {"username": "git"},
              {"password": "${{ secrets.TECH_TOKEN }}"},
              {"scmpublish.pubScmUrl": "scm:git:${{ github.event.repository.clone_url}}"},
              {"scmpublish.dryRun": "false"}
            ]
          cache-prefix: ${{ needs.setup.outputs.date-ym }}-maven-site-

      - run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Action"

      - run: mvn --errors --show-version package site-deploy -Dmaven.test.skip=true

  publish-release:
    name: Publish Release
    concurrency: release-drafter

    if: github.repository_owner == 's4u' && startsWith(github.ref, 'refs/tags/')

    needs: [ setup, site-deploy ]
    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@v6.1.0
        with:
          publish: false
          name: ${{ needs.setup.outputs.tag }}
          tag: ${{ needs.setup.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
