name: Release Drafter

on:
  workflow_call:

jobs:
  detect-version:
    name: Detect version

    if: >
      github.repository_owner == 's4u'
      && !startsWith(github.event.head_commit.message , '[maven-release-plugin]')

    runs-on: ubuntu-latest
    concurrency: release-drafter
    permissions: {}
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: 'false'

      - id: has-pom
        run: |
          if [ -f pom.xml ]; then
            echo "status=true" >> $GITHUB_OUTPUT
          fi
          cat $GITHUB_OUTPUT

      - uses: actions/setup-java@v5
        if: steps.has-pom.outputs.status == 'true'
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'

      - id: version
        if: steps.has-pom.outputs.status == 'true'
        run: |
          mvn --batch-mode --non-recursive help:evaluate -Dexpression=project.version -Doutput=target/version.txt
          V=$(cat target/version.txt)
          echo "version=${V%-SNAPSHOT}" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    concurrency: release-drafter
    permissions:
      contents: write
    needs: detect-version

    steps:

      - uses: release-drafter/release-drafter@v6.1.0
        with:
          version: ${{ needs.detect-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
